### PR TITLE
Reword passive aggressive contributing statement to something more welcoming

### PR DESCRIPTION
**Pull request by JosephWoodward**

### CODE REVIEW

**Comment by martincostello** [comment]
@JosephWoodward Worth investigating also adding the various GitHub community docs for contributing, PR template etc.?

**Comment by martincostello** [comment]
Their being two Stus continues to baffle me 🤣

**Comment by stuart-lang** [comment]
I don't see what's confusing

**Comment by slang25** [comment]
Neither do I

**Pull request merged**
