### PR TITLE
Adding naming strategy support

### PR DESCRIPTION
**Pull request by dariusdamalakas**
Adds an extension point to allow to pass in custom queue and topic naming strategy. Additionally, fixes issue #79 - multiple badly named extra queues were crated for SQS subscriber.

Added extra Sample project to solution.

### CODE REVIEW

**Comment by Edu115** [comment]
@brainmurphy Really curious on the status of this pull request. 

Our team is currently using JustSaying, and we are stuck with the same use case, where we need to define custom topic names for different environments.
Either this or #87 would allow us to do it, any idea which one will be eventually be merged back to master?

Cheers!

**Comment by payman81** [comment]
@Edu115 it is currently possible to override the strategy for generating topic names and queue names. You would need to extend IPublishEndpointProvider and IPublishSubscribtionEndpointProvider for topic names and queue names respectively. Here is an example of how to customise topic name https://github.com/justeat/JustSaying/issues/75#issuecomment-100840888.

**Comment by dariusdamalakas** [comment]
@payman81, are you guys still using [gitter](https://gitter.im/justeat/JustSaying) ?    This PR has been for since 24th Jul, neither approved nor rejected.

**Comment by payman81** [comment]
@dariusdamalakas - We had some issues with merging this without breaking change on our side. However, we think this is a valid change and we are going to look at this again later this week.

**Comment by dariusdamalakas** [comment]
@payman81 , ok, thanks for confirming.  Don't merge it please. It's not up to maintainers to fix broken PRs. I will rebase this, and will update this PR. Will let you know here once this is done.

**Comment by dariusdamalakas** [comment]
@payman81 , have rebased this commit. Have a look now. Also, it's been a while since I ran integration tests for this branch. So if you could run all tests and let me know if there are any failing tests, that would be great. Thanks.

**Pull request merged**
