### PR TITLE
Feature/improve arn parsing and IAM Policy testability

### PR DESCRIPTION
**Pull request by PeterKneale**
- I noticed `SnsPolicy.cs` was using regex to parse the source ARN instead of using Amazons supplied `ARN.Parse(..)` method.
- Before changing this I separated the two responsibilities of `generating` and `applying` the policy
- This allowed me to add an `approval test` against the IAM policy generated
- Then I made the actual change and introduced `ARN.Parse(..)` and observed no regressions.
- I also added a mechanism to validate the ARN I saw elsewhere.

### CODE REVIEW

**Comment by PeterKneale** [comment]
Is this sort of small improvement okay to add without a ticket - Please let me know if I overstep :)

**Comment by PeterKneale** [comment]
I can do the same for `SqsPolicy` if desired

**Review by slang25 — APPROVED** [review]
Nice!

**Comment by slang25** [comment]
Thanks for this @PeterKneale, these improvements are always appreciated 🙂. We don't mind skipping issues when there isn't a design discussion to be had.

**Pull request merged**
