### PR TITLE
Normalize line endings

### PR DESCRIPTION
**Pull request by slang25**
With credit to @martincostello for the gitattribute specifics. If we merge this and I do the same for #426, it should be much easier to review.

### CODE REVIEW

**Comment by slang25** [comment]
Yep https://github.com/justeat/JustSaying/pull/441/files?w=1

Pro-tip: don't open the regular diff on your phone

**Comment by slang25** [comment]
@adammorr could you please re-approve please, I forced pushed to retrigger appveyor, which didn't respond to the first commit for some reason.

**Comment by adammorr** [comment]
@slang25 it is done

**Comment by martincostello** [comment]
My eyes! 🙈

**Comment by AnthonySteele** [comment]
@martincostello `Diff settings|Hide whitespace changes`

**Comment by martincostello** [comment]
Still have to see it before you change the option 😉

**Pull request merged**
