### PR TITLE
Update goaws

### PR DESCRIPTION
**Pull request by slang25**
Bare with me, I'm doing this from a phone

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Still failing in IntegrationTests on travis.

**Comment by slang25** [comment]
Yeah, I think the current change is needed (the loopback for goaws.com) and we'll probably need add an accountid to the config, and there may still be a change required to goaws to get it working again (possible missing route). See here:
https://github.com/p4tin/goaws/issues/187

**Comment by p4tin** [comment]
I am working on a fix for goaws to make the router problem go away...  Stil doing some tests to make sure and updating the unit tests should be out with version 1.1.2 by tomorrow.

**Comment by slang25** [comment]
Nice one @p4tin 😄

**Comment by slang25** [comment]
Great job @p4tin, works great!

**Pull request merged**
