### PR TITLE
ToLowerInvariant

### PR DESCRIPTION
**Pull request by AnthonySteele**
_Summarise the changes this Pull Request makes._

use `ToLowerInvariant()` not `ToLower()` throughout.
This should be a compatible change in almost all cases, whereas using `ToUpperInvariant()` as some guidance suggests, could introduce tricky breakages.

_Please include a reference to a GitHub issue if appropriate._

Work towards using code analysers

### CODE REVIEW

**Comment by martincostello** [comment]
Relates to #401.

**Comment by slang25** [comment]
I am putting together a blog post that goes into this rule, I think it's BS. There are some characters that don't round trip when you go from source->lower->upper, but also some that don't round trip when you do source->upper->lower. The perf difference is not worth talking about either, so this is good 👍

**Comment by slang25** [comment]
Related, there are places we should use `CultureInfo.InvariantCulture` and `StringComparison.Ordinal` in a few places

**Comment by martincostello** [comment]
@slang25 I believe @AnthonySteele is doing PRs to fix one rule at a time.

**Pull request merged**
