### PR TITLE
Add IAM actions to README

### PR DESCRIPTION
**Pull request by adammorr**
_Summarise the changes this Pull Request makes._
Pull out the required IAM actions from release notes and add them to the README.

- https://github.com/justeat/JustSaying/releases/tag/v5.0.0
- https://github.com/justeat/JustSaying/releases/tag/v6.0.0

### CODE REVIEW

**Comment by martincostello** [comment]
Nice. Maybe we should include an example IAM policy document somewhere too?

**Comment by adammorr** [comment]
@martincostello good point, I'll add one in

**Comment by adammorr** [comment]
I've excluded `sns:ListSubscriptionsByTopic` as I don't believe this is required any longer for two reasons;

- My tests didn't fail when I removed this
- I _think_ we removed the check for an existing topic subscription if favour of subscribing a queue each time, regardless of whether it exists already

Does the 2nd point ring a bell to anyone?

**Comment by adammorr** [comment]
No more amendments from me on this @martincostello, promise!

**Comment by martincostello** [comment]
@adammorr Now you definitely can't 😉

**Comment by slang25** [comment]
@adammorr You are right, there was a change that improved startup perf by doing what you described.
We should probably remove this line here in the default SNS policy:
https://github.com/justeat/JustSaying/blob/master/JustSaying/AwsTools/MessageHandling/SnsPolicy.cs#L49

**Pull request merged**
