### PR TITLE
Listener per queue per region

### PR DESCRIPTION
**Pull request by dariusdamalakas**

### CODE REVIEW

**Comment by brainmurphy** [comment]
@dariusdamalakas I think you need to merge master and resolve conflicts before I can merge this.

**Comment by dariusdamalakas** [comment]
@brainmurphy you sure about this? Sure, can go ahead and merge this into IntelliFlo:master. Will do that now.

**Comment by dariusdamalakas** [comment]
@brainmurphy , updated.

**Comment by brainmurphy** [comment]
Compilation failure, @dariusdamalakas ;-)

JustSayingFluently\AddingHandlers\WhenAddingASubscriptionHandlerForAGenericMessage.cs(37, 13): error CS1501: No overload for method 'AddMessageHandler' takes 1 arguments

**Comment by dariusdamalakas** [comment]
Shame on me for merging master, and forgetting to check it all still works.

**Pull request merged**
