### PR TITLE
Message serialisation refactoring.

### PR DESCRIPTION
**Pull request by dariusdamalakas**
Allows IMessageSerialiser to take complete control of message serialisation/deserialisation. This allows to handle AWS SES notifications.

Subject and Message properties are no longer mandatory, different IMessageSerialiser implementation can take other approaches to deserialise messages.

See issue #80 for details.

### CODE REVIEW

**Comment by payman81** [comment]
Thanks @dariusdamalakas for the contribution. PR looks good and passed my backward compatibility tests.

**Comment by dariusdamalakas** [comment]
@payman81 thanks.  Are these backward compat tests part of the JustSaying solution, or is something that you have on your own machine? I'd be interested in setting up a travis or appveyor continuos builds, so that we could see whether tests pass or not.

**Comment by payman81** [comment]
In addition of existing tests in the solution, I usually run the latest version in one of my components in an integration environment. 
As discussed in a different thread, moving to appveyor and making the build pipeline visible publicly is highly desirable.

**Comment by petemounce** [comment]
@payman81 come find me tomorrow. I have existing automation and configuration for appveyor that ought to make that a very quick wire-up.

**Pull request merged**
