### PR TITLE
Update INamingStrategy.GetQueueName to take SqsReadConfiguration for …

### PR DESCRIPTION
**Pull request by payman81**
…easier extension.

### CODE REVIEW

**Comment by payman81** [comment]
@brainmurphy Submitted this PR as discussed.

**Comment by brainmurphy** [comment]
@payman81 Actually, I think that we wanted to make SqsReadConfiguration.InstancePosition public.

**Comment by payman81** [comment]
I checked and it was public already https://github.com/justeat/JustSaying/blob/master/JustSaying.AwsTools/QueueCreation/SqsReadConfiguration.cs#L30 cc @brainmurphy

**Comment by brainmurphy** [comment]
Oh, bugger, it's SubscriptionType I was thinking of! We need that to distinguish between whether we're subscribing to SQS directly or to SQS-subscribed-to-SNS.

**Pull request merged**
