### PR TITLE
Using AWS SDK Version 3

### PR DESCRIPTION
**Pull request by Liewe**
As discussed with my colleague (@edu115) we updated the AWS SDK to version 3.
The only real change we did was in SqsQueueByName.cs:

We would get an error in unittest WhenOptingOutOfErrorQueue.ErrorQueueShouldNotBeCreated:
"Value {"maxReceiveCount":"5", "deadLetterTargetArn":""} for parameter RedrivePolicy is invalid. Reason: Invalid value for deadLetterTargetArn.".
Since this only happens when opting out of an errorqueue and without an error queue you don't need a redrive policy, we moved the call to UpdateRedrivePolicy to within the errorqueue create/update condition block.

### CODE REVIEW

**Comment by AnthonySteele** [comment]
Hi, do you want to update this PR for current master? I looked at it and the conficts is easy to fix - just 1 line in `SqsQueueByName.cs`.

**Comment by slang25** [comment]
@Liewe We'd like this to be merged to the develop branch, which will be where we'll be adding features to become v5.

**Comment by Liewe** [comment]
I'll have a look in monday.

**Comment by Liewe** [comment]
I upmerged master. @slang25 I created a new pullrequest targeting the develop branch:  https://github.com/justeat/JustSaying/pull/222

**Comment by slang25** [comment]
Closing in favor of #222. Thanks @Liewe!

**Pull request closed without merging**
