### PR TITLE
Use nunit test adapter

### PR DESCRIPTION
**Pull request by slang25**

### CODE REVIEW

**Comment by martincostello** [comment]
Looks good. Can we get Travis to run the tests now too?

**Comment by slang25** [comment]
We'd have to run them with mono for now until deps are migrated right now, not sure how many would pass.
I'll check the status of our test dependencies cause we might be close to getting the tests to run on core, we might need to migrate off of JustBehave, or rewrite to use something else (BDDfy?)

**Comment by martincostello** [comment]
Ah fair enough, I thought all that stuff had been pulled out already.

**Comment by slang25** [comment]
Unfortunately not. I did have a go and then gave up. It looks like JustBehave can be ported pretty soon, the AutoFixture port is done and just needs merging to master and deploying, once that is done I think we are good to go. That might be easier than replacing it with something like BDDfy, although if someone comes along and does this, I'll merge it ( @shaynevanasperen ).

I'll be happy when you can just pull this down on Windows, macOS or Linux and it all just works and you can happily dev away 😃

**Comment by AnthonySteele** [comment]
Good to go?

**Comment by slang25** [comment]
@AnthonySteele Yes please

**Pull request merged**
